[package]
name = "cfm"
version = "0.1.0"
authors = ["Nils <nils@nilsand.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
structopt = "0.3.21"
